on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: JExpenseTracker # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'ftp://waws-prod-dm1-185.ftp.azurewebsites.windows.net/site/wwwroot' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x' # set this to the node version to use

jobs:
  build-and-deploy:
  if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          action: "upload"
          output_location: "dist/dashboard" # Built app content directory - optional
